import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    const copy={en:{eyebrow:'Interactive engineering map · 01',title:'The life of a bug report.',lead:'From “something feels off” to shipped and solved. Choose each branch and watch the incident path unfold.',map:'Incident map',work:'Work',decision:'Decision',terminal:'Start / close',control:'Flow control',progress:'Progress',current:'Current stage',begin:'Begin triage →',loops:'Loops',resolved:'Resolved',reset:'Reset incident',received:'Report received',footer:'Designed for clarity, built for every screen.'},ro:{eyebrow:'Hartă interactivă de engineering · 01',title:'Viața unui raport de eroare.',lead:'De la „ceva nu funcționează” până la rezolvare și lansare. Alege fiecare ramură și urmărește traseul incidentului.',map:'Harta incidentului',work:'Acțiune',decision:'Decizie',terminal:'Start / închidere',control:'Controlul fluxului',progress:'Progres',current:'Etapa curentă',begin:'Începe verificarea →',loops:'Reveniri',resolved:'Rezolvat',reset:'Resetează incidentul',received:'Raport primit',footer:'Creat pentru claritate, pe orice ecran.'}};
    Object.assign(copy.en,{labEyebrow:'Mermaid diagram lab · 02',labTitle:'Mermaid, charted.',labLead:'Explore four more diagram types, copy their source, then build your own in the live editor.',sequenceTitle:'Sequence: a login request',sequenceText:'Follow a sign-in request between the user, browser, API, and database.',stateTitle:'State: a support ticket',stateText:'See how a ticket moves between statuses, including waiting and reopening loops.',ganttTitle:'Gantt: a two-week sprint',ganttText:'Turn tasks, dates, and dependencies into a clear delivery timeline.',gitTitle:'Git graph: a feature branch',gitText:'Explain commits, branches, hotfixes, and merges through a visual history.',editorTitle:'Your turn: live editor',editorText:'Type Mermaid source on the left and watch the preview update.',hint:'Tip: every diagram starts with its keyword: flowchart, sequenceDiagram, stateDiagram-v2, gantt, or gitGraph.'});
    Object.assign(copy.ro,{labEyebrow:'Laborator de diagrame Mermaid · 02',labTitle:'Mermaid, pus în diagramă.',labLead:'Explorează încă patru tipuri, copiază sursa și construiește propria diagramă în editor.',sequenceTitle:'Secvență: o cerere de autentificare',sequenceText:'Urmărește autentificarea între utilizator, browser, API și baza de date.',stateTitle:'Stări: un tichet de suport',stateText:'Vezi cum trece un tichet prin stări, inclusiv buclele de așteptare și redeschidere.',ganttTitle:'Gantt: un sprint de două săptămâni',ganttText:'Transformă sarcinile, datele și dependențele într-un calendar clar.',gitTitle:'Git graph: o ramură de funcționalitate',gitText:'Explică commituri, ramuri, hotfixuri și îmbinări printr-un istoric vizual.',editorTitle:'Acum e rândul tău: editor live',editorText:'Scrie sursa Mermaid în stânga și urmărește actualizarea previzualizării.',hint:'Sfat: fiecare diagramă începe cu propriul cuvânt-cheie: flowchart, sequenceDiagram, stateDiagram-v2, gantt sau gitGraph.'});
    const stages={start:{en:'Bug report comes in',ro:'Raportul de eroare sosește',next:['repro']},repro:{en:'Can you reproduce it?',ro:'Poți reproduce eroarea?',next:['info','fix'],decision:true},info:{en:'Ask reporter for details',ro:'Cere detalii persoanei care a raportat',next:['repro'],loop:true},fix:{en:'Write a fix',ro:'Scrie rezolvarea',next:['test']},test:{en:'Do the tests pass?',ro:'Testele trec?',next:['fix','review'],decision:true,loop:true},review:{en:'Code review',ro:'Verificarea codului',next:['ship']},ship:{en:'Deploy',ro:'Publicare',next:['done']},done:{en:'Close the ticket ✦',ro:'Închide tichetul ✦',next:[]}};
    let lang='en',current='start',visited=['start'],loops=0;
    const $=s=>document.querySelector(s), status=$('#status'),choices=$('#choices'),timeline=$('#timeline'),bar=$('#bar'),progress=$('.progress'),progressText=$('#progressText');
    mermaid.initialize({startOnLoad:true,securityLevel:'loose',theme:'base',flowchart:{curve:'basis',htmlLabels:true},themeVariables:{fontFamily:'Public Sans',lineColor:'#8290aa'}});
    await mermaid.run(); highlight();
    function nodeEl(id){return document.querySelector(`[id*="flowchart-${id}-"]`)||document.querySelector(`[id$="-${id}-0"]`)}
    function highlight(){document.querySelectorAll('.node').forEach(n=>n.classList.remove('active','completed'));visited.forEach(id=>nodeEl(id)?.classList.add('completed'));nodeEl(current)?.classList.add('active')}
    function choiceLabel(from,to,index){if(from==='repro')return index===0?(lang==='ro'?'Nu — cer detalii':'No — ask for details'):(lang==='ro'?'Da — scrie rezolvarea':'Yes — write the fix');if(from==='test')return index===0?(lang==='ro'?'Nu — înapoi la cod':'No — back to code'):(lang==='ro'?'Da — trimite la review':'Yes — send to review');return `${stages[to][lang]} →`}
    function render(){status.textContent=stages[current][lang];choices.replaceChildren();stages[current].next.forEach((to,i)=>{const b=document.createElement('button');b.className='choice';b.dataset.kind=stages[current].decision?(i?'yes':'no'):'';b.textContent=choiceLabel(current,to,i);b.onclick=()=>go(to);choices.append(b)});if(current==='done'){const s=document.createElement('div');s.className='status-box';s.innerHTML=lang==='ro'?'Rezolvat și publicat. <strong>Bravo! 🎉</strong>':'Resolved and shipped. <strong>Nice work! 🎉</strong>';choices.append(s)}const pct=current==='done'?100:Math.min(95,Math.round((new Set(visited).size/8)*100));bar.style.width=pct+'%';progress.setAttribute('aria-valuenow',Math.min(9,visited.length));progressText.textContent=`${Math.min(9,visited.length)} / 9`;$('#attempts').textContent=loops;$('#resolved').textContent=pct+'%';highlight()}
    function go(next){if((current==='info'&&next==='repro')||(current==='test'&&next==='fix'))loops++;current=next;visited.push(next);const li=document.createElement('li');li.textContent=stages[next][lang];timeline.prepend(li);render()}
    $('#reset').onclick=()=>{current='start';visited=['start'];loops=0;timeline.innerHTML=`<li>${copy[lang].received}</li>`;render()};
    $('#lang').onclick=()=>{lang=lang==='en'?'ro':'en';document.documentElement.lang=lang;$('#lang').textContent=lang==='en'?'RO':'EN';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=copy[lang][el.dataset.i18n]);[...timeline.children].forEach(()=>{});render()};
    let labId=0,editorTimer;
    const editorInput=$('#editor-input'),editorOutput=$('#editor-output');
    async function renderMermaid(src,target){try{const {svg}=await mermaid.render(`lab-${labId++}`,src.trim());target.innerHTML=svg}catch(error){target.textContent=error?.message||String(error);target.classList.add('editor-error')}}
    async function renderLab(){for(const fig of document.querySelectorAll('[data-diagram]'))await renderMermaid(fig.querySelector('.mermaid-source').textContent,fig.querySelector('.diagram-render'));await renderMermaid(editorInput.value,editorOutput)}
    const templates=[
      {name:'Bug triage',cat:'Development',type:'flowchart',src:'flowchart TD\n  A[Report] --> B{Reproduce?}\n  B -- No --> C[Ask details]\n  C --> B\n  B -- Yes --> D[Fix]\n  D --> E[Test]\n  E --> F[Deploy]'},
      {name:'CRM lead pipeline',cat:'CRM',type:'state',src:'stateDiagram-v2\n  [*] --> NewLead\n  NewLead --> Qualified\n  Qualified --> Proposal\n  Proposal --> Won\n  Proposal --> Lost\n  Won --> [*]'},
      {name:'Login request',cat:'Development',type:'sequence',src:'sequenceDiagram\n  actor User\n  participant App\n  participant API\n  User->>App: Sign in\n  App->>API: POST /login\n  API-->>App: Session\n  App-->>User: Dashboard'},
      {name:'Database schema',cat:'Data',type:'ER',src:'erDiagram\n  CUSTOMER ||--o{ ORDER : places\n  ORDER ||--|{ ITEM : contains\n  CUSTOMER {\n    string email\n    string name\n  }'},
      {name:'Product sprint',cat:'Planning',type:'gantt',src:'gantt\n  title Product sprint\n  dateFormat YYYY-MM-DD\n  section Design\n  Research :a1, 2026-09-08, 3d\n  Prototype :after a1, 3d\n  section Build\n  Development :2026-09-14, 5d\n  QA :2d'},
      {name:'Campaign journey',cat:'Marketing',type:'journey',src:'journey\n  title Campaign journey\n  section Discover\n    See campaign: 4: Customer\n    Visit landing page: 5: Customer\n  section Convert\n    Submit form: 4: Customer\n    Receive offer: 5: Customer'},
      {name:'Content mix',cat:'Marketing',type:'pie',src:'pie title Content mix\n  "Education" : 45\n  "Product" : 30\n  "Community" : 25'},
      {name:'Release history',cat:'Development',type:'gitGraph',src:'gitGraph\n  commit id: "setup"\n  branch feature\n  commit id: "build"\n  checkout main\n  merge feature\n  commit id: "release"'},
      {name:'Product roadmap',cat:'Planning',type:'timeline',src:'timeline\n  title Product roadmap\n  Q3 : Research : Prototype\n  Q4 : Build : Beta\n  Q1 : Launch : Measure'},
      {name:'Feature map',cat:'Planning',type:'mindmap',src:'mindmap\n  root((Product))\n    CRM\n      Leads\n      Clients\n    Automation\n      Email\n      Tasks'},
      {name:'Team roles',cat:'Development',type:'class',src:'classDiagram\n  Team <|-- Designer\n  Team <|-- Developer\n  class Team {\n    +name\n    +deliver()\n  }'},
      {name:'Priority matrix',cat:'Planning',type:'quadrant',src:'quadrantChart\n  title Impact vs effort\n  x-axis Low effort --> High effort\n  y-axis Low impact --> High impact\n  quadrant-1 Strategic\n  quadrant-2 Quick wins\n  A: [0.25, 0.85]\n  B: [0.70, 0.60]'}
    ];
    let history=[editorInput.value],historyIndex=0,zoom=1,activeCategory='All';
    const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800)};
    function saveDraft(){localStorage.setItem('bugflow-draft',editorInput.value);$('#save-state').textContent=lang==='ro'?'Salvat local':'Saved locally'}
    function pushHistory(){if(history[historyIndex]===editorInput.value)return;history=history.slice(0,historyIndex+1);history.push(editorInput.value);historyIndex=history.length-1;if(history.length>50){history.shift();historyIndex--}}
    async function updateEditor(){editorOutput.classList.remove('editor-error');$('#diagram-status').textContent='Rendering…';await renderMermaid(editorInput.value,editorOutput);$('#diagram-status').textContent=editorOutput.classList.contains('editor-error')?'Error':'Ready';saveDraft()}
    editorInput.addEventListener('input',()=>{pushHistory();$('#save-state').textContent='Editing…';clearTimeout(editorTimer);editorTimer=setTimeout(updateEditor,400)});
    function setSource(src){editorInput.value=src;pushHistory();updateEditor();editorInput.scrollIntoView({behavior:'smooth',block:'center'});toast(lang==='ro'?'Șablon încărcat':'Template loaded')}
    function renderTemplates(){const q=$('#template-search').value.toLowerCase();const grid=$('#template-grid');grid.replaceChildren();templates.filter(t=>(activeCategory==='All'||t.cat===activeCategory)&&t.name.toLowerCase().includes(q)).forEach(t=>{const b=document.createElement('button');b.className='template-card';b.innerHTML=`<span class="template-type">${t.type}</span><strong>${t.name}</strong><small>${t.cat}</small>`;b.onclick=()=>setSource(t.src);grid.append(b)})}
    [...new Set(['All',...templates.map(t=>t.cat)])].forEach(cat=>{const b=document.createElement('button');b.textContent=cat;b.classList.toggle('active',cat==='All');b.onclick=()=>{activeCategory=cat;document.querySelectorAll('#template-filters button').forEach(x=>x.classList.toggle('active',x===b));renderTemplates()};$('#template-filters').append(b)});$('#template-search').oninput=renderTemplates;renderTemplates();
    function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
    async function exportPng(){const svg=editorOutput.querySelector('svg');if(!svg)return toast('Nothing to export');const data=new XMLSerializer().serializeToString(svg);const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=Math.max(1200,img.width*2);c.height=Math.max(800,img.height*2);const ctx=c.getContext('2d');ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--surface');ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download(b,'bugflow-diagram.png'))};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(data)}
    document.querySelector('.studio-toolbar').onclick=async e=>{const action=e.target.dataset.action;if(!action)return;if(action==='undo'&&historyIndex>0){editorInput.value=history[--historyIndex];updateEditor()}if(action==='redo'&&historyIndex<history.length-1){editorInput.value=history[++historyIndex];updateEditor()}if(action==='format'){editorInput.value=editorInput.value.split('\n').map(x=>x.trimEnd()).join('\n').trim();pushHistory();updateEditor()}if(action==='copy'){await navigator.clipboard.writeText(editorInput.value);toast('Source copied')}if(action==='download-mmd')download(new Blob([editorInput.value],{type:'text/plain'}),'bugflow-diagram.mmd');if(action==='download-svg'){const svg=editorOutput.querySelector('svg');if(svg)download(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'}),'bugflow-diagram.svg')}if(action==='download-png')exportPng();if(action==='share'){const data={title:'Bugflow diagram',text:editorInput.value,url:location.href};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('Link copied')}}if(action==='zoom-in'||action==='zoom-out'){zoom=Math.min(2,Math.max(.5,zoom+(action==='zoom-in'?.1:-.1)));editorOutput.style.transform=`scale(${zoom})`;$('#zoom-level').textContent=Math.round(zoom*100)+'%'}if(action==='fit'){zoom=1;editorOutput.style.transform='scale(1)';$('#zoom-level').textContent='100%'}if(action==='fullscreen'){document.fullscreenElement?document.exitFullscreen():$('#studio-editor').requestFullscreen()}};
    const defaultProject={id:crypto.randomUUID(),name:'My first diagram',source:editorInput.value,updated:Date.now()};let projects=JSON.parse(localStorage.getItem('bugflow-projects')||'null')||[defaultProject],activeProject=localStorage.getItem('bugflow-active')||projects[0].id;let stats=JSON.parse(localStorage.getItem('bugflow-stats')||'{"xp":0,"renders":0}');
    function persistProjects(){const p=projects.find(x=>x.id===activeProject);if(p){p.source=editorInput.value;p.updated=Date.now()}localStorage.setItem('bugflow-projects',JSON.stringify(projects));localStorage.setItem('bugflow-active',activeProject)}
    function renderProjectSelect(){const s=$('#project-select');s.replaceChildren();projects.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;o.selected=p.id===activeProject;s.append(o)})}
    function loadProject(id){persistProjects();activeProject=id;const p=projects.find(x=>x.id===id);if(!p)return;editorInput.value=p.source;history=[p.source];historyIndex=0;localStorage.setItem('bugflow-active',id);updateEditor();renderProjectSelect()}
    $('#project-select').onchange=e=>loadProject(e.target.value);$('#new-project').onclick=()=>{const name=prompt('Project name','Untitled diagram');if(!name)return;const p={id:crypto.randomUUID(),name,source:'flowchart TD\n  A([Start]) --> B([Finish])',updated:Date.now()};projects.push(p);activeProject=p.id;loadProject(p.id)};$('#rename-project').onclick=()=>{const p=projects.find(x=>x.id===activeProject),name=prompt('New name',p.name);if(name){p.name=name;persistProjects();renderProjectSelect()}};$('#duplicate-project').onclick=()=>{const p=projects.find(x=>x.id===activeProject),copyProject={...p,id:crypto.randomUUID(),name:p.name+' copy',updated:Date.now()};projects.push(copyProject);activeProject=copyProject.id;loadProject(activeProject)};$('#delete-project').onclick=()=>{if(projects.length===1)return toast('Keep at least one project');if(confirm('Delete this project?')){projects=projects.filter(x=>x.id!==activeProject);activeProject=projects[0].id;loadProject(activeProject)}};$('#backup-projects').onclick=()=>download(new Blob([JSON.stringify({version:1,projects},null,2)],{type:'application/json'}),'bugflow-backup.json');
    $('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();try{const data=JSON.parse(text);if(Array.isArray(data.projects)){projects.push(...data.projects.map(p=>({...p,id:crypto.randomUUID()})));activeProject=projects.at(-1).id;loadProject(activeProject);toast('Backup imported');return}}catch{}const p={id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),source:text,updated:Date.now()};projects.push(p);activeProject=p.id;loadProject(p.id)};editorInput.addEventListener('input',()=>setTimeout(persistProjects,450));renderProjectSelect();
    function describeDiagram(){const lines=editorInput.value.split('\n').map(x=>x.trim()).filter(Boolean);const kind=lines[0]||'diagram';const relations=lines.slice(1).filter(x=>/-->|->>|-->>|-->/.test(x));const labels=[...editorInput.value.matchAll(/[\[({]\[?([^\]\)\}]+)[\]\)\}]/g)].map(m=>m[1].replace(/[\[\]()]/g,''));const description=`${kind} with ${new Set(labels).size||'several'} named elements and ${relations.length} connections. ${relations.slice(0,6).join('; ')}${relations.length>6?'…':''}`;$('#accessible-description').textContent=description;return description}
    function award(points){stats.xp+=points;stats.renders++;localStorage.setItem('bugflow-stats',JSON.stringify(stats));$('#xp').textContent=stats.xp;$('#diagram-count').textContent=stats.renders;$('#badge').textContent=stats.xp>=300?'Architect':stats.xp>=100?'Builder':'Explorer'}award(0);
    $('#generate-diagram').onclick=e=>{e.preventDefault();const parts=$('#ai-prompt').value.split(/,|->|→|\n/).map(x=>x.trim()).filter(Boolean);if(!parts.length)return;const nodes=parts.map((p,i)=>`${String.fromCharCode(65+i)}${p.endsWith('?')?`{${p}}`:`[${p}]`}`);let src='flowchart TD\n';for(let i=0;i<nodes.length;i++){src+='  '+nodes[i]+(i<nodes.length-1?` --> ${String.fromCharCode(66+i)}`:'')+'\n'}setSource(src.trim());$('#ai-dialog').close();award(25)};
    document.querySelector('.studio-toolbar').addEventListener('click',async e=>{const a=e.target.dataset.action;if(a==='ai')$('#ai-dialog').showModal();if(a==='describe'){describeDiagram();award(5)}if(a==='speak'){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(describeDiagram()))}if(a==='print')window.print();if(a==='download-html'){const svg=editorOutput.querySelector('svg');if(svg)download(new Blob([`<!doctype html><meta charset="utf-8"><title>Bugflow diagram</title><style>body{display:grid;place-items:center;min-height:100vh;font-family:system-ui}</style>${svg.outerHTML}`],{type:'text/html'}),'bugflow-diagram.html')}if(a==='download-webp'){const svg=editorOutput.querySelector('svg');if(!svg)return;const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=Math.max(1200,img.width*2);c.height=Math.max(800,img.height*2);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download(b,'bugflow-diagram.webp'),'image/webp',.92)};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(svg))}});
    $('#node-search').oninput=e=>{const q=e.target.value.toLowerCase();editorOutput.querySelectorAll('.node').forEach(n=>n.classList.toggle('search-hit',q&&n.textContent.toLowerCase().includes(q)))};

    const snapshots=()=>JSON.parse(localStorage.getItem('bugflow-snapshots')||'[]');
    $('#snapshot-project').onclick=()=>{const list=snapshots();list.unshift({id:crypto.randomUUID(),project:activeProject,name:projects.find(p=>p.id===activeProject)?.name||'Diagram',source:editorInput.value,date:new Date().toISOString()});localStorage.setItem('bugflow-snapshots',JSON.stringify(list.slice(0,30)));toast('Snapshot saved');award(10)};
    $('#history-project').onclick=()=>{const list=snapshots().filter(x=>x.project===activeProject),box=$('#snapshot-list');box.innerHTML=list.length?list.map(x=>`<button type="button" data-snapshot="${x.id}"><strong>${x.name}</strong><small>${new Date(x.date).toLocaleString()}</small></button>`).join(''):'<p>No snapshots yet.</p>';box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const item=list.find(x=>x.id===b.dataset.snapshot);if(item){setSource(item.source);$('#history-dialog').close();toast('Snapshot restored')}});$('#history-dialog').showModal()};
    $('#theme-custom').onclick=()=>$('#theme-dialog').showModal();const customTheme=JSON.parse(localStorage.getItem('bugflow-theme')||'{}');function applyCustomTheme(t=customTheme){if(t.accent)document.documentElement.style.setProperty('--blue',t.accent);if(t.surface)document.documentElement.style.setProperty('--surface',t.surface)}applyCustomTheme();$('#theme-save').onclick=()=>{customTheme.accent=$('#accent-color').value;customTheme.surface=$('#surface-color').value;localStorage.setItem('bugflow-theme',JSON.stringify(customTheme));applyCustomTheme();toast('Theme saved')};$('#theme-reset').onclick=()=>{localStorage.removeItem('bugflow-theme');document.documentElement.style.removeProperty('--blue');document.documentElement.style.removeProperty('--surface')};
    $('#editor-lines').textContent=editorInput.value.split('\n').length+' lines';editorInput.addEventListener('input',()=>$('#editor-lines').textContent=editorInput.value.split('\n').length+' lines');
    let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-app').hidden=false});$('#install-app').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install-app').hidden=true};const network=()=>{$('#network-status').textContent=navigator.onLine?'Online':'Offline';$('#network-status').classList.toggle('offline',!navigator.onLine)};addEventListener('online',network);addEventListener('offline',network);network();
    document.querySelector('.studio-toolbar').addEventListener('click',e=>{const a=e.target.dataset.action;if(a==='download-md')download(new Blob([`# ${projects.find(p=>p.id===activeProject)?.name||'Diagram'}\n\n\`\`\`mermaid\n${editorInput.value}\n\`\`\`\n`],{type:'text/markdown'}),'bugflow-diagram.md');if(a==='download-json')download(new Blob([JSON.stringify({name:projects.find(p=>p.id===activeProject)?.name||'Diagram',source:editorInput.value,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}),'bugflow-diagram.json')});
    document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveDraft();persistProjects();toast('Saved')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();const action=e.shiftKey?'redo':'undo';document.querySelector(`[data-action="${action}"]`).click()}if(e.key==='Escape')$('#a11y-panel').hidden=true});
    const savedDraft=localStorage.getItem('bugflow-draft');if(savedDraft){editorInput.value=savedDraft;history=[savedDraft]}
    const prefs=JSON.parse(localStorage.getItem('bugflow-prefs')||'{}');function applyPrefs(){document.documentElement.style.fontSize=(prefs.size||100)+'%';document.documentElement.classList.toggle('high-contrast',!!prefs.contrast);document.documentElement.classList.toggle('easy-read',!!prefs.font);document.documentElement.classList.toggle('reduce-motion',!!prefs.motion);localStorage.setItem('bugflow-prefs',JSON.stringify(prefs))}$('#a11y').onclick=()=>{$('#a11y-panel').hidden=false};$('#a11y-close').onclick=()=>{$('#a11y-panel').hidden=true};$('#text-size').value=prefs.size||100;$('#contrast').checked=!!prefs.contrast;$('#simple-font').checked=!!prefs.font;$('#motion').checked=!!prefs.motion;$('#text-size').oninput=e=>{prefs.size=e.target.value;applyPrefs()};$('#contrast').onchange=e=>{prefs.contrast=e.target.checked;applyPrefs()};$('#simple-font').onchange=e=>{prefs.font=e.target.checked;applyPrefs()};$('#motion').onchange=e=>{prefs.motion=e.target.checked;applyPrefs()};$('#reset-prefs').onclick=()=>{Object.keys(prefs).forEach(k=>delete prefs[k]);applyPrefs();location.reload()};applyPrefs();
    document.querySelectorAll('.copy-btn').forEach(btn=>btn.addEventListener('click',async()=>{const src=btn.closest('[data-diagram]').querySelector('.mermaid-source').textContent;try{await navigator.clipboard.writeText(src);btn.textContent=lang==='ro'?'Copiat':'Copied';btn.classList.add('copied')}catch{btn.textContent='Ctrl+C'}setTimeout(()=>{btn.textContent=lang==='ro'?'Copiază':'Copy';btn.classList.remove('copied')},1500)}));
    $('#theme').onclick=async()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';document.querySelector('meta[name="theme-color"]').content=dark?'#0b1020':'#f5f6fa';mermaid.initialize({startOnLoad:false,securityLevel:'loose',theme:dark?'dark':'base',flowchart:{curve:'basis',htmlLabels:true},themeVariables:{fontFamily:'Public Sans',lineColor:dark?'#aab5ca':'#8290aa'}});await renderLab()};
    const builderShapes={terminal:{label:'Terminal',icon:'⬭',wrap:t=>`(["${t}"])`},process:{label:'Process',icon:'▭',wrap:t=>`["${t}"]`},decision:{label:'Decision',icon:'◇',wrap:t=>`{"${t}"`+'}'},data:{label:'Data',icon:'▱',wrap:t=>`[/"${t}"/]`},database:{label:'Database',icon:'◉',wrap:t=>`[("${t}")]`},note:{label:'Note',icon:'⌑',wrap:t=>`["${t}"]`}};
    const builderPresets={
      bug:{direction:'TD',nodes:[['A','Bug arrives','terminal'],['B','Reproduce?','decision'],['C','Ask for details','process'],['D','Write a fix','process'],['E','Tests pass?','decision'],['F','Deploy','process'],['G','Close ticket','terminal']],edges:[['A','B',''],['B','C','No'],['C','B',''],['B','D','Yes'],['D','E',''],['E','D','No'],['E','F','Yes'],['F','G','']]},
      release:{direction:'LR',nodes:[['A','Idea','terminal'],['B','Specification','process'],['C','Approved?','decision'],['D','Build','process'],['E','QA','process'],['F','Ship','terminal']],edges:[['A','B',''],['B','C',''],['C','B','No'],['C','D','Yes'],['D','E',''],['E','F','']]},
      crm:{direction:'TD',nodes:[['A','New lead','terminal'],['B','Qualified?','decision'],['C','Nurture','process'],['D','Proposal','data'],['E','Won','terminal']],edges:[['A','B',''],['B','C','No'],['C','B','Retry'],['B','D','Yes'],['D','E','']]}
    };
    let builder={direction:'TD',nodes:[],edges:[],zoom:1,custom:null,runTimer:null,positions:JSON.parse(localStorage.getItem('bugflow-builder-layout')||'{}')};
    const safeText=value=>String(value).replace(/["\n\r]/g,' ').trim().slice(0,80);
    const safeHtml=value=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
    const nextBuilderId=()=>{for(let i=0;i<702;i++){const id=i<26?String.fromCharCode(65+i):String.fromCharCode(65+Math.floor((i-26)/26))+String.fromCharCode(65+(i-26)%26);if(!builder.nodes.some(n=>n.id===id))return id}return 'N'+Date.now()};
    function builderSource(){if(builder.custom)return builder.custom;const rows=[`flowchart ${builder.direction}`];builder.nodes.forEach(n=>rows.push(`  ${n.id}${builderShapes[n.shape]?.wrap(safeText(n.text))||builderShapes.process.wrap(safeText(n.text))}`));builder.edges.forEach(e=>{if(builder.nodes.some(n=>n.id===e.from)&&builder.nodes.some(n=>n.id===e.to))rows.push(`  ${e.from} -->${e.label?`|"${safeText(e.label)}"|`:''} ${e.to}`)});return rows.join('\n')}
    async function renderBuilder(){const source=builderSource();$('#builder-source').value=source;$('#builder-stat-nodes').textContent=$('#builder-node-count').textContent=builder.nodes.length;$('#builder-stat-edges').textContent=$('#builder-edge-count').textContent=builder.edges.length;$('#builder-stat-direction').textContent=builder.direction;$('#builder-direction').value=builder.direction;try{const {svg}=await mermaid.render(`builder-${labId++}`,source);$('#builder-canvas').innerHTML=svg;enableBuilderDrag();$('#flow-status').textContent='Flow ready'}catch(error){$('#builder-canvas').textContent=String(error?.message||error).split('\n')[0];$('#flow-status').textContent='Check the source'}applyBuilderZoom()}

    function enableBuilderDrag(){const canvas=$('#builder-canvas');canvas.querySelectorAll('.node').forEach(node=>{const raw=node.id.match(/flowchart-([^-]+)-/)?.[1];if(!raw)return;const saved=builder.positions[raw]||{x:0,y:0};node.style.transform=`translate(${saved.x}px,${saved.y}px)`;node.style.cursor='move';let start=null;node.onpointerdown=e=>{if(e.button!==0)return;start={x:e.clientX,y:e.clientY,ox:saved.x,oy:saved.y};node.setPointerCapture(e.pointerId);e.preventDefault()};node.onpointermove=e=>{if(!start)return;saved.x=start.ox+(e.clientX-start.x)/builder.zoom;saved.y=start.oy+(e.clientY-start.y)/builder.zoom;node.style.transform=`translate(${saved.x}px,${saved.y}px)`};node.onpointerup=()=>{start=null;builder.positions[raw]={...saved};localStorage.setItem('bugflow-builder-layout',JSON.stringify(builder.positions))}})}
    function drawBuilderLists(){const options=builder.nodes.map(n=>`<option value="${n.id}">${n.id}</option>`).join('');$('#builder-nodes').innerHTML=builder.nodes.map((n,i)=>`<div class="builder-item" data-index="${i}" draggable="true"><code>${n.id}</code><input data-field="text" aria-label="Node ${n.id} label" value="${safeHtml(n.text)}"><button data-remove-node="${i}" aria-label="Delete node ${n.id}">×</button></div>`).join('');$('#builder-edges').innerHTML=builder.edges.map((e,i)=>`<div class="builder-edge" data-index="${i}"><select data-field="from" aria-label="Connection start">${options.replace(`value="${e.from}"`,`value="${e.from}" selected`)}</select><span>→</span><select data-field="to" aria-label="Connection end">${options.replace(`value="${e.to}"`,`value="${e.to}" selected`)}</select><input data-field="label" aria-label="Connection label" placeholder="Label" value="${safeHtml(e.label)}"><button data-remove-edge="${i}" aria-label="Delete connection">×</button></div>`).join('')}
    function loadBuilderPreset(name){const p=builderPresets[name]||builderPresets.bug;stopBuilderFlow();builder.direction=p.direction;builder.nodes=p.nodes.map(([id,text,shape])=>({id,text,shape}));builder.edges=p.edges.map(([from,to,label])=>({from,to,label}));builder.custom=null;drawBuilderLists();renderBuilder()}
    function scheduleBuilder(){builder.custom=null;clearTimeout(scheduleBuilder.timer);scheduleBuilder.timer=setTimeout(renderBuilder,180)}
    Object.entries(builderShapes).forEach(([key,value])=>{const b=document.createElement('button');b.type='button';b.className='shape-chip';b.dataset.shape=key;b.innerHTML=`<span aria-hidden="true">${value.icon}</span>${value.label}`;$('#shape-palette').append(b)});
    $('#shape-palette').onclick=e=>{const button=e.target.closest('[data-shape]');if(!button)return;const id=nextBuilderId(),last=builder.nodes.at(-1);builder.nodes.push({id,text:builderShapes[button.dataset.shape].label,shape:button.dataset.shape});if(last)builder.edges.push({from:last.id,to:id,label:''});drawBuilderLists();scheduleBuilder()};
    $('#builder-nodes').oninput=e=>{const item=e.target.closest('.builder-item');if(!item)return;builder.nodes[+item.dataset.index][e.target.dataset.field]=e.target.value;scheduleBuilder()};
    $('#builder-nodes').onclick=e=>{if(e.target.dataset.removeNode===undefined)return;const i=+e.target.dataset.removeNode,id=builder.nodes[i].id;builder.nodes.splice(i,1);builder.edges=builder.edges.filter(x=>x.from!==id&&x.to!==id);drawBuilderLists();scheduleBuilder()};
    $('#builder-edges').oninput=e=>{const item=e.target.closest('.builder-edge');if(!item)return;builder.edges[+item.dataset.index][e.target.dataset.field]=e.target.value;scheduleBuilder()};
    $('#builder-edges').onclick=e=>{if(e.target.dataset.removeEdge===undefined)return;builder.edges.splice(+e.target.dataset.removeEdge,1);drawBuilderLists();scheduleBuilder()};
    $('#builder-add-edge').onclick=()=>{if(builder.nodes.length<2)return toast('Add at least two nodes');builder.edges.push({from:builder.nodes[0].id,to:builder.nodes[1].id,label:''});drawBuilderLists();scheduleBuilder()};
    $('#builder-direction').onchange=e=>{builder.direction=e.target.value;scheduleBuilder()};$('#builder-preset').onchange=e=>loadBuilderPreset(e.target.value);
    document.querySelector('.builder-tabs').onclick=e=>{const tab=e.target.closest('[data-builder-tab]');if(!tab)return;document.querySelectorAll('[data-builder-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===tab)));document.querySelectorAll('.builder-pane').forEach(x=>x.classList.remove('active'));$(`#builder-${tab.dataset.builderTab}-pane`).classList.add('active')};
    $('#builder-apply').onclick=async()=>{builder.custom=$('#builder-source').value;await renderBuilder();toast('Source applied')};
    $('#builder-sync').onclick=()=>{const src=$('#builder-source').value,dir=src.match(/(?:flowchart|graph)\s+(TD|TB|LR|BT|RL)/i);if(dir)builder.direction=dir[1]==='TB'?'TD':dir[1];const nodes=[];for(const match of src.matchAll(/^\s*([A-Za-z][\w]*)\s*(\(\[|\[\(|\[\/|\{|\[)(?:"?)(.*?)(?:"?)(\]\)|\)\]|\/\]|\}|\])\s*$/gm)){const [,id,open,text]=match;nodes.push({id,text,shape:open==='{ '? 'decision':open==='{'?'decision':open==='(['?'terminal':open==='[('?'database':open==='[/'?'data':'process'})}const edges=[...src.matchAll(/^\s*([A-Za-z][\w]*)\s*-->\s*(?:\|"?(.*?)"?\|\s*)?([A-Za-z][\w]*)/gm)].map(([,from,label='',to])=>({from,to,label}));if(nodes.length){builder.nodes=nodes;builder.edges=edges;builder.custom=null;drawBuilderLists();renderBuilder();toast('Blocks synchronized')}else toast('No compatible flowchart nodes found')};
    $('#builder-copy').onclick=async()=>{await navigator.clipboard.writeText($('#builder-source').value);toast('Builder source copied')};
    function applyBuilderZoom(){builder.zoom=Math.min(2.4,Math.max(.4,builder.zoom));$('#builder-canvas').style.transform=`scale(${builder.zoom})`;$('#builder-zoom').textContent=Math.round(builder.zoom*100)+'%'}
    $('#builder-zoom-in').onclick=()=>{builder.zoom+=.15;applyBuilderZoom()};$('#builder-zoom-out').onclick=()=>{builder.zoom-=.15;applyBuilderZoom()};$('#builder-fit').onclick=()=>{builder.zoom=1;applyBuilderZoom()};
    function stopBuilderFlow(){clearInterval(builder.runTimer);builder.runTimer=null;$('#builder-stage').classList.remove('running');$('#pressure-bar').style.width='0';$('#flow-status').textContent='Ready to flow'}
    $('#builder-play').onclick=()=>{stopBuilderFlow();$('#builder-stage').classList.add('running');let pressure=0;$('#flow-status').textContent='Pipeline running…';builder.runTimer=setInterval(()=>{pressure+=Math.max(5,100/Math.max(4,builder.edges.length));$('#pressure-bar').style.width=Math.min(100,pressure)+'%';if(pressure>=100){clearInterval(builder.runTimer);builder.runTimer=null;$('#flow-status').textContent='Route completed ✦';award(15);setTimeout(()=>$('#builder-stage').classList.remove('running'),1000)}},300)};$('#builder-stop').onclick=stopBuilderFlow;
    $('#builder-theme').onclick=()=>{const vellum=$('#visual-builder').classList.toggle('vellum');$('#builder-theme').textContent=vellum?'Blueprint':'Vellum'};
    $('#builder-to-editor').onclick=()=>{setSource(builderSource());award(20)};
    loadBuilderPreset('bug');
    render();await renderLab();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
